[package]
name = "zbus-lockstep"
authors = ["Luuk van der Duim <luukvanderduim@gmail.com>", "Tait Hoyem<tait@tait.tech>"]
description = "Keep types in lockstep with DBus XML definitions"
version = "0.1.0"
edition = "2021"
keywords = ["type-safety", "zbus", "DBus", "IPC"]
categories = ["API-bindings"]
documentation = "https://docs.rs/zbus-lockstep"
repository = "https://github.com/luukvanderduim/zbus-lockstep"
readme = "README.md"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "LICENSE*", "README.md"]
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = { version = "3", features = ["xml"] }

[dev-dependencies]
tempfile = "3.7"